[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[template.environment]
    BIGCOMMERCE_STOREFRONT_API_URL="BIGCOMMERCE_STOREFRONT_API_URL"
    BIGCOMMERCE_STOREFRONT_API_TOKEN="BIGCOMMERCE_STOREFRONT_API_TOKEN"
    BIGCOMMERCE_STORE_API_URL="BIGCOMMERCE_STORE_API_URL"
    BIGCOMMERCE_STORE_API_TOKEN="BIGCOMMERCE_STORE_API_TOKEN"
    BIGCOMMERCE_STORE_API_CLIENT_ID="BIGCOMMERCE_STORE_API_CLIENT_ID"
    BIGCOMMERCE_STORE_API_STORE_HASH="BIGCOMMERCE_STORE_API_STORE_HASH"
    BIGCOMMERCE_STORE_URL="BIGCOMMERCE_STORE_URL"
    BIGCOMMERCE_CHANNEL_ID="BIGCOMMERCE_CHANNEL_ID"
    CONTENTSTACK_API_KEY="CONTENTSTACK_API_KEY"
    CONTENTSTACK_ACCESS_TOKEN="CONTENTSTACK_ACCESS_TOKEN"

